In [438]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import torch
import NeuralNetwork as NN
import Layer
import importlib
importlib.reload(NN)
importlib.reload(Layer)

<module 'Layer' from '/Users/jorchard/Dropbox/research/peBogacz/python/Layer.py'>

In [446]:
net = NN.NeuralNetwork()
l = Layer.InputPELayer(n=2)
net.AddLayer(l)
net.AddLayer(Layer.PELayer(n=2))
net.AddLayer(Layer.PELayer(n=2))

In [453]:
net.SetIdentityWeights()
net.SetInput([1., 0])

In [454]:
net.ShowState()

Layer 0 (input):
  v = [1. 0.]
  e = [0. 0.]
Layer 1:
  v = [0. 0.]
  e = [0. 0.]
Layer 2:
  v = [0. 0.]
  e = [0. 0.]


In [455]:
net.Integrate()
net.Step(dt=0.1)

In [456]:
net.ShowState()

Layer 0 (input):
  v = [1. 0.]
  e = [0.02310586 0.        ]
Layer 1:
  v = [0. 0.]
  e = [0. 0.]
Layer 2:
  v = [0. 0.]
  e = [0. 0.]


In [457]:
net.ShowWeights()

  W01 = 
[[1. 0.]
 [0. 1.]]
  M10 = 
[[1. 0.]
 [0. 1.]]
  W12 = 
[[1. 0.]
 [0. 1.]]
  M21 = 
[[1. 0.]
 [0. 1.]]


In [465]:
T = 10
dt = 0.1
tt = np.arange(0, T, dt)

In [475]:
net.Run(T, dt=dt)
net.ShowState()

Layer 0 (input):
  v = [1. 0.]
  e = [5.048212e-05 0.000000e+00]
Layer 1:
  v = [0.9997643 0.       ]
  e = [3.1188956e-05 0.0000000e+00]
Layer 2:
  v = [0.99961877 0.        ]
  e = [0. 0.]
